import { ProcurementTicket } from '@/types'

export const mockProcurementTickets: ProcurementTicket[] = [
  {
    id: "PT-001",
    ticketId: "PT-001",
    title: "Office Supplies - Q1 2024",
    requester: "Sarah Johnson",
    department: "Administration",
    amount: 2500.0,
    status: "approved",
    priority: "medium",
    date: "2024-01-15",
    createdDate: "2024-01-15",
    createdAt: "2024-01-15T08:00:00Z",
    description: "Quarterly office supplies including paper, pens, and stationery",
    materials: [],
    comments: [],
  },
  {
    id: "PT-002",
    ticketId: "PT-002",
    title: "Software Licenses Renewal",
    requester: "Mike Chen",
    department: "IT",
    amount: 15000.0,
    status: "pending",
    priority: "high",
    date: "2024-01-20",
    createdDate: "2024-01-20",
    createdAt: "2024-01-20T09:00:00Z",
    description: "Annual renewal for Microsoft Office and Adobe Creative Suite licenses",
    materials: [],
    comments: [],
  },
  {
    id: "PT-003",
    ticketId: "PT-003",
    title: "Marketing Campaign Materials",
    requester: "Emily Davis",
    department: "Marketing",
    amount: 8500.0,
    status: "in-progress",
    priority: "medium",
    date: "2024-01-18",
    createdDate: "2024-01-18",
    createdAt: "2024-01-18T10:00:00Z",
    description: "Print materials and promotional items for Q2 campaign",
    materials: [],
    comments: [],
  },
  {
    id: "PT-004",
    ticketId: "PT-004",
    title: "New Laptop Computers",
    requester: "David Wilson",
    department: "IT",
    amount: 12000.0,
    status: "rejected",
    priority: "low",
    date: "2024-01-10",
    createdDate: "2024-01-10",
    createdAt: "2024-01-10T11:00:00Z",
    description: "5 new laptops for development team - budget exceeded",
    materials: [],
    comments: [],
  },
  {
    id: "PT-005",
    ticketId: "PT-005",
    title: "Conference Room Furniture",
    requester: "Lisa Brown",
    department: "Facilities",
    amount: 4200.0,
    status: "approved",
    priority: "medium",
    date: "2024-01-22",
    createdDate: "2024-01-22",
    createdAt: "2024-01-22T12:00:00Z",
    description: "New conference table and chairs for meeting room B",
    materials: [],
    comments: [],
  },
  {
    id: "PT-006",
    ticketId: "PT-006",
    title: "Training Workshop Materials",
    requester: "John Smith",
    department: "HR",
    amount: 1800.0,
    status: "in-progress",
    priority: "low",
    date: "2024-01-25",
    createdDate: "2024-01-25",
    createdAt: "2024-01-25T13:00:00Z",
    description: "Materials and resources for employee training sessions",
    materials: [],
    comments: [],
  },
  {
    id: "PT-007",
    ticketId: "PT-007",
    title: "Security System Upgrade",
    requester: "Robert Taylor",
    department: "Security",
    amount: 25000.0,
    status: "pending",
    priority: "high",
    date: "2024-01-28",
    createdDate: "2024-01-28",
    createdAt: "2024-01-28T14:00:00Z",
    description: "Upgrade building security cameras and access control system",
    materials: [],
    comments: [],
  },
] 