import { ProcurementTicket } from "@/types/procurement"

export const mockProcurementTickets: ProcurementTicket[] = [
  {
    id: "PT-001",
    ticketId: "PT-001",
    title: "Office Supplies - Q1 2024",
    requester: { id: "user_1", fullName: "Sarah Johnson", email: "sarah.j@example.com" },
    department: "Administration",
    amount: 2500.0,
    status: "approved",
    priority: "medium",
    date: "2024-01-15",
    createdDate: "2024-01-15",
    createdAt: "2024-01-15T08:00:00Z",
    description: "Quarterly office supplies including paper, pens, and stationery",
    salesManager: "SJ",
    telefon: "123-456-7890",
    profitcenter: "PC-001",
    customerName: "ACME Corp",
    customerCVR: "12345678",
    customerOrderNumber: "CUST-001",
    salesOrg: "SO-1",
    distributionChannel: "DC-1",
    salesOffice: "OFF-1",
    salesGroup: "SG-1",
    localReportingCode: "LRC-1",
    prodHierarchy: "PH-1",
    company: "ACME Corp",
    attention: "Procurement Dept",
    roadNumber: "123 Main St",
    materials: [],
    comments: [],
  },
  {
    id: "PT-002",
    ticketId: "PT-002",
    title: "Software Licenses Renewal",
    requester: { id: "user_2", fullName: "Mike Chen", email: "mike.c@example.com" },
    department: "IT",
    amount: 15000.0,
    status: "pending",
    priority: "high",
    date: "2024-01-20",
    createdDate: "2024-01-20",
    createdAt: "2024-01-20T09:00:00Z",
    description: "Annual renewal for Microsoft Office and Adobe Creative Suite licenses",
    salesManager: "MC",
    telefon: "123-456-7891",
    profitcenter: "PC-002",
    customerName: "Tech Solutions",
    customerCVR: "87654321",
    customerOrderNumber: "CUST-002",
    salesOrg: "SO-2",
    distributionChannel: "DC-2",
    salesOffice: "OFF-2",
    salesGroup: "SG-2",
    localReportingCode: "LRC-2",
    prodHierarchy: "PH-2",
    company: "Tech Solutions",
    attention: "IT Dept",
    roadNumber: "456 Tech Ave",
    materials: [],
    comments: [],
  },
  {
    id: "PT-003",
    ticketId: "PT-003",
    title: "Marketing Campaign Materials",
    requester: { id: "user_3", fullName: "Emily Davis", email: "emily.d@example.com" },
    department: "Marketing",
    amount: 8500.0,
    status: "in-progress",
    priority: "medium",
    date: "2024-01-18",
    createdDate: "2024-01-18",
    createdAt: "2024-01-18T10:00:00Z",
    description: "Print materials and promotional items for Q2 campaign",
    salesManager: "ED",
    telefon: "123-456-7892",
    profitcenter: "PC-003",
    customerName: "Creative Co",
    customerCVR: "11223344",
    customerOrderNumber: "CUST-003",
    salesOrg: "SO-3",
    distributionChannel: "DC-3",
    salesOffice: "OFF-3",
    salesGroup: "SG-3",
    localReportingCode: "LRC-3",
    prodHierarchy: "PH-3",
    company: "Creative Co",
    attention: "Marketing Dept",
    roadNumber: "789 Design Dr",
    materials: [],
    comments: [],
  },
  {
    id: "PT-004",
    ticketId: "PT-004",
    title: "New Laptop Computers",
    requester: { id: "user_4", fullName: "David Wilson", email: "david.w@example.com" },
    department: "IT",
    amount: 12000.0,
    status: "rejected",
    priority: "low",
    date: "2024-01-10",
    createdDate: "2024-01-10",
    createdAt: "2024-01-10T11:00:00Z",
    description: "5 new laptops for development team - budget exceeded",
    salesManager: "DW",
    telefon: "123-456-7893",
    profitcenter: "PC-004",
    customerName: "Dev Team",
    customerCVR: "55667788",
    customerOrderNumber: "CUST-004",
    salesOrg: "SO-4",
    distributionChannel: "DC-4",
    salesOffice: "OFF-4",
    salesGroup: "SG-4",
    localReportingCode: "LRC-4",
    prodHierarchy: "PH-4",
    company: "Internal",
    attention: "IT Dept",
    roadNumber: "101 Code Lane",
    materials: [],
    comments: [],
  },
  {
    id: "PT-005",
    ticketId: "PT-005",
    title: "Conference Room Furniture",
    requester: { id: "user_5", fullName: "Lisa Brown", email: "lisa.b@example.com" },
    department: "Facilities",
    amount: 4200.0,
    status: "approved",
    priority: "medium",
    date: "2024-01-22",
    createdDate: "2024-01-22",
    createdAt: "2024-01-22T12:00:00Z",
    description: "New conference table and chairs for meeting room B",
    salesManager: "LB",
    telefon: "123-456-7894",
    profitcenter: "PC-005",
    customerName: "Facilities Dept",
    customerCVR: "99887766",
    customerOrderNumber: "CUST-005",
    salesOrg: "SO-5",
    distributionChannel: "DC-5",
    salesOffice: "OFF-5",
    salesGroup: "SG-5",
    localReportingCode: "LRC-5",
    prodHierarchy: "PH-5",
    company: "Internal",
    attention: "Facilities",
    roadNumber: "202 Maintenance Ave",
    materials: [],
    comments: [],
  },
  {
    id: "PT-006",
    ticketId: "PT-006",
    title: "Training Workshop Materials",
    requester: { id: "user_1", fullName: "John Smith", email: "john.s@example.com" },
    department: "HR",
    amount: 1800.0,
    status: "in-progress",
    priority: "low",
    date: "2024-01-25",
    createdDate: "2024-01-25",
    createdAt: "2024-01-25T13:00:00Z",
    description: "Materials and resources for employee training sessions",
    salesManager: "JS",
    telefon: "123-456-7895",
    profitcenter: "PC-006",
    customerName: "HR Dept",
    customerCVR: "12121212",
    customerOrderNumber: "CUST-006",
    salesOrg: "SO-6",
    distributionChannel: "DC-6",
    salesOffice: "OFF-6",
    salesGroup: "SG-6",
    localReportingCode: "LRC-6",
    prodHierarchy: "PH-6",
    company: "Internal",
    attention: "HR",
    roadNumber: "303 Training Rd",
    materials: [],
    comments: [],
  },
  {
    id: "PT-007",
    ticketId: "PT-007",
    title: "Security System Upgrade",
    requester: { id: "user_6", fullName: "Robert Taylor", email: "robert.t@example.com" },
    department: "Security",
    amount: 25000.0,
    status: "pending",
    priority: "high",
    date: "2024-01-28",
    createdDate: "2024-01-28",
    createdAt: "2024-01-28T14:00:00Z",
    description: "Upgrade building security cameras and access control system",
    salesManager: "RT",
    telefon: "123-456-7896",
    profitcenter: "PC-007",
    customerName: "Security Dept",
    customerCVR: "34343434",
    customerOrderNumber: "CUST-007",
    salesOrg: "SO-7",
    distributionChannel: "DC-7",
    salesOffice: "OFF-7",
    salesGroup: "SG-7",
    localReportingCode: "LRC-7",
    prodHierarchy: "PH-7",
    company: "Internal",
    attention: "Security",
    roadNumber: "404 Secure St",
    materials: [],
    comments: [],
  },
] 