import {
  IconProps,
  IconBrandGithub,
  IconBrandTwitter,
  IconCheck,
  IconCommand,
  IconX,
  IconLoader,
  IconChevronLeft,
  IconChevronRight,
  IconTrash,
  IconFileText,
  IconFile,
  IconPhoto,
  IconSettings,
  IconCreditCard,
  IconDots,
  IconPlus,
  IconAlertCircle,
  IconUser,
  IconUserEdit,
  IconArrowRight,
  IconHelpCircle,
  IconPizza,
  IconLogin,
  IconLayoutDashboard,
  IconChartBar,
  IconShoppingCart,
  IconLayoutKanban,
  IconMessage,
  IconFolder,
  IconInbox,
  IconSend,
  IconArchive,
  IconArchiveOff,
  IconCopy,
  IconUsers,
  IconMoon,
  IconSun,
  IconDeviceLaptop
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  logo: IconCommand,
  close: IconX,
  spinner: IconLoader,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  post: IconFileText,
  page: IconFile,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDots,
  add: IconPlus,
  warning: IconAlertCircle,
  user: IconUser,
  userPen: IconUserEdit,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  login: IconLogin,
  gitHub: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  dashboard: IconLayoutDashboard,
  analytics: IconChartBar,
  product: IconShoppingCart,
  kanban: IconLayoutKanban,
  message: IconMessage,
  projects: IconFolder,
  inbox: IconInbox,
  send: IconSend,
  archive: IconArchive,
  archiveX: IconArchiveOff,
  copy: IconCopy,
  users: IconUsers,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop
};
